<?php
require_once(dirname(__FILE__).'/config.php'); 
require_once(dirname(__FILE__).'/utils.php');
require_once(dirname(__FILE__).'/db/db.php');
require_once(dirname(__FILE__).'/db/basedn.php');
require_once(dirname(__FILE__).'/db/objects.php');
require_once(dirname(__FILE__).'/controllers/ldap-controller.php');
require_once(dirname(__FILE__).'/controllers/setting-controller.php');
require_once(dirname(__FILE__).'/controllers/user-controller.php');
require_once(dirname(__FILE__).'/controllers/group-controller.php');
require_once(dirname(__FILE__).'/controllers/organization-controller.php');
require_once(dirname(__FILE__).'/controllers/translate-controller.php'); 
?>