<?php
require_once(dirname(__FILE__).'/vendor/autoload.php');
require_once(dirname(__FILE__).'/config.php');
require_once(dirname(__FILE__).'/i18n/vi.php');
require_once(dirname(__FILE__).'/utils.php');
require_once(dirname(__FILE__).'/controller/user-controller.php');
require_once(dirname(__FILE__).'/controller/group-controller.php');
require_once(dirname(__FILE__).'/controller/role-controller.php');
require_once(dirname(__FILE__).'/controller/translate-controller.php');
?>